### ISSUE TITLE
smbus2 not installed by one line installer

### ISSUE THREAD

**Issue by helgibbons** [pimoroni/inky#64]
`curl https://get.pimoroni.com/inky | bash` doesn't currently install the smbus2 dependency needed to run the name-badge.py example.  Can we get this included?

The error that the example generates suggests running `sudo pip install smbus2` (even when using Python 3) but I needed to run `sudo pip3 install smbus2` to grab the right version.

**Comment by Gadgetoid** [comment]
This is because `smbus2` is only required by the `rpi-gpio-output` and/or `rpi` install options.

```
    install_requires=['numpy'],
    extras_require={
        'rpi-gpio-output': ['spidev', 'RPi.GPIO', 'smbus2'],
        'rpi': ['spidev', 'RPi.GPIO', 'smbus2'],
        'fonts': ['font-fredoka-one', 'font-source-serif-pro', 'font-hanken-grotesk', 'font-intuitive'],
        'example-depends': ['requests', 'geocoder', 'beautifulsoup4']
    }
```

This happened when the Inky simulator code- that lets you run a fake Inky on your desktop for development- was merged in.

I think it's safer just to install these in all cases and risk breaking things for the small number of people who will use the simulator, rather than confusing things for the large number of people who will use this with the Pi! I will change it.
